/* automatically generated from actions-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (actions_dialog_ui)
#endif
#ifdef __GNUC__
static const char actions_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char actions_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\"?><interface><requires lib=\"gtk+\" version=\"2.14"
  "\"/><object class=\"XfceTitledDialog\" id=\"dialog\"><property name=\"t"
  "itle\" translatable=\"yes\">Action Buttons</property><property name=\"i"
  "con_name\">gtk-properties</property><property name=\"type_hint\">normal"
  "</property><property name=\"has_separator\">False</property><child inte"
  "rnal-child=\"vbox\"><object class=\"GtkVBox\" id=\"dialog-vbox1\"><prop"
  "erty name=\"visible\">True</property><property name=\"orientation\">ver"
  "tical</property><property name=\"spacing\">2</property><child><object c"
  "lass=\"GtkFrame\" id=\"frame5\"><property name=\"visible\">True</proper"
  "ty><property name=\"border_width\">6</property><property name=\"label_x"
  "align\">0</property><property name=\"shadow_type\">none</property><chil"
  "d><object class=\"GtkAlignment\" id=\"alignment5\"><property name=\"vis"
  "ible\">True</property><property name=\"left_padding\">12</property><chi"
  "ld><object class=\"GtkTable\" id=\"table5\"><property name=\"visible\">"
  "True</property><property name=\"border_width\">6</property><property na"
  "me=\"n_rows\">2</property><property name=\"n_columns\">2</property><pro"
  "perty name=\"column_spacing\">12</property><property name=\"row_spacing"
  "\">6</property><child><object class=\"GtkLabel\" id=\"label8\"><propert"
  "y name=\"visible\">True</property><property name=\"xalign\">0</property"
  "><property name=\"label\" translatable=\"yes\">_First button:</property"
  "><property name=\"use_underline\">True</property><property name=\"mnemo"
  "nic_widget\">first-action</property></object><packing><property name=\""
  "x_options\">GTK_FILL</property><property name=\"y_options\">GTK_FILL</p"
  "roperty></packing></child><child><object class=\"GtkLabel\" id=\"label9"
  "\"><property name=\"visible\">True</property><property name=\"xalign\">"
  "0</property><property name=\"label\" translatable=\"yes\">_Second butto"
  "n:</property><property name=\"use_underline\">True</property><property "
  "name=\"mnemonic_widget\">second-action</property></object><packing><pro"
  "perty name=\"top_attach\">1</property><property name=\"bottom_attach\">"
  "2</property><property name=\"x_options\">GTK_FILL</property><property n"
  "ame=\"y_options\">GTK_FILL</property></packing></child><child><object c"
  "lass=\"GtkComboBox\" id=\"first-action\"><property name=\"visible\">Tru"
  "e</property><property name=\"model\">first-action-model</property><chil"
  "d><object class=\"GtkCellRendererText\" id=\"cellrenderertext2\"/><attr"
  "ibutes><attribute name=\"text\">0</attribute></attributes></child></obj"
  "ect><packing><property name=\"left_attach\">1</property><property name="
  "\"right_attach\">2</property></packing></child><child><object class=\"G"
  "tkComboBox\" id=\"second-action\"><property name=\"visible\">True</prop"
  "erty><property name=\"model\">second-action-model</property><child><obj"
  "ect class=\"GtkCellRendererText\" id=\"cellrenderertext1\"/><attributes"
  "><attribute name=\"text\">0</attribute></attributes></child></object><p"
  "acking><property name=\"left_attach\">1</property><property name=\"righ"
  "t_attach\">2</property><property name=\"top_attach\">1</property><prope"
  "rty name=\"bottom_attach\">2</property></packing></child></object></chi"
  "ld></object></child><child type=\"label\"><object class=\"GtkLabel\" id"
  "=\"label7\"><property name=\"visible\">True</property><property name=\""
  "label\" translatable=\"yes\">Button Actions</property><attributes><attr"
  "ibute name=\"weight\" value=\"bold\"/></attributes></object></child></o"
  "bject><packing><property name=\"expand\">False</property><property name"
  "=\"position\">1</property></packing></child><child internal-child=\"act"
  "ion_area\"><object class=\"GtkHButtonBox\" id=\"dialog-action_area1\"><"
  "property name=\"visible\">True</property><property name=\"layout_style\""
  ">end</property><child><object class=\"GtkButton\" id=\"close-button\"><"
  "property name=\"label\">gtk-close</property><property name=\"visible\">"
  "True</property><property name=\"can_focus\">True</property><property na"
  "me=\"receives_default\">True</property><property name=\"use_stock\">Tru"
  "e</property></object><packing><property name=\"expand\">False</property"
  "><property name=\"fill\">False</property><property name=\"position\">0<"
  "/property></packing></child><child><object class=\"GtkButton\" id=\"hel"
  "p-button\"><property name=\"label\">gtk-help</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">True</property><property name=\"use_s"
  "tock\">True</property></object><packing><property name=\"expand\">False"
  "</property><property name=\"fill\">False</property><property name=\"pos"
  "ition\">1</property><property name=\"secondary\">True</property></packi"
  "ng></child></object><packing><property name=\"expand\">False</property>"
  "<property name=\"pack_type\">end</property><property name=\"position\">"
  "0</property></packing></child></object></child><action-widgets><action-"
  "widget response=\"0\">close-button</action-widget><action-widget respon"
  "se=\"0\">help-button</action-widget></action-widgets></object><object c"
  "lass=\"GtkListStore\" id=\"first-action-model\"><columns><column type=\""
  "gchararray\"/></columns></object><object class=\"GtkListStore\" id=\"se"
  "cond-action-model\"><columns><column type=\"gchararray\"/></columns></o"
  "bject></interface>"
};

static const unsigned actions_dialog_ui_length = 4958u;

