/* automatically generated from panel-preferences-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (panel_preferences_dialog_ui)
#endif
#ifdef __GNUC__
static const char panel_preferences_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char panel_preferences_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\"?><interface><requires lib=\"gtk+\" version=\"2.14"
  "\"/><object class=\"GtkListStore\" id=\"orientation-store\"><columns><c"
  "olumn type=\"gchararray\"/></columns><data><row><col id=\"0\" translata"
  "ble=\"yes\">Vertical</col></row><row><col id=\"0\" translatable=\"yes\""
  ">Horizontal</col></row></data></object><object class=\"GtkListStore\" i"
  "d=\"panel-store\"><columns><column type=\"gchararray\"/></columns></obj"
  "ect><object class=\"GtkListStore\" id=\"output-store\"><columns><column"
  " type=\"gchararray\"/><column type=\"gchararray\"/></columns></object><"
  "object class=\"GtkListStore\" id=\"styles-store\"><columns><column type"
  "=\"gchararray\"/></columns><data><row><col id=\"0\" translatable=\"yes\""
  ">None (use system style)</col></row><row><col id=\"0\" translatable=\"y"
  "es\">Solid color</col></row><row><col id=\"0\" translatable=\"yes\">Bac"
  "kground image</col></row></data></object><object class=\"GtkAdjustment\""
  " id=\"size\"><property name=\"value\">16</property><property name=\"low"
  "er\">16</property><property name=\"upper\">128</property><property name"
  "=\"step_increment\">1</property><property name=\"page_increment\">10</p"
  "roperty></object><object class=\"GtkAdjustment\" id=\"length\"><propert"
  "y name=\"value\">25</property><property name=\"lower\">1</property><pro"
  "perty name=\"upper\">100</property><property name=\"step_increment\">1<"
  "/property><property name=\"page_increment\">10</property></object><obje"
  "ct class=\"GtkAdjustment\" id=\"background-alpha\"><property name=\"val"
  "ue\">100</property><property name=\"upper\">100</property><property nam"
  "e=\"step_increment\">1</property><property name=\"page_increment\">10</"
  "property></object><object class=\"GtkAdjustment\" id=\"enter-opacity\">"
  "<property name=\"value\">100</property><property name=\"upper\">100</pr"
  "operty><property name=\"step_increment\">1</property><property name=\"p"
  "age_increment\">10</property></object><object class=\"GtkAdjustment\" i"
  "d=\"leave-opacity\"><property name=\"value\">100</property><property na"
  "me=\"upper\">100</property><property name=\"step_increment\">1</propert"
  "y><property name=\"page_increment\">10</property></object><object class"
  "=\"GtkSizeGroup\" id=\"display-sizegroup\"><widgets><widget name=\"labe"
  "l13\"/><widget name=\"label1\"/></widgets></object><object class=\"GtkS"
  "izeGroup\" id=\"bg-sizegroup\"><widgets><widget name=\"label7\"/><widge"
  "t name=\"label15\"/><widget name=\"label16\"/><widget name=\"label19\"/"
  "></widgets></object><object class=\"XfceTitledDialog\" id=\"dialog\"><p"
  "roperty name=\"title\" translatable=\"yes\">Panel</property><property n"
  "ame=\"window_position\">center-on-parent</property><property name=\"ico"
  "n_name\">heartlenv-panel</property><property name=\"type_hint\">normal</pro"
  "perty><property name=\"has_separator\">False</property><child internal-"
  "child=\"vbox\"><object class=\"GtkVBox\" id=\"dialog-vbox1\"><property "
  "name=\"visible\">True</property><property name=\"orientation\">vertical"
  "</property><property name=\"spacing\">2</property><child><object class="
  "\"GtkVBox\" id=\"vbox1\"><property name=\"visible\">True</property><pro"
  "perty name=\"border_width\">6</property><property name=\"orientation\">"
  "vertical</property><property name=\"spacing\">12</property><child><obje"
  "ct class=\"GtkHBox\" id=\"hbox3\"><property name=\"visible\">True</prop"
  "erty><property name=\"spacing\">6</property><child><object class=\"GtkC"
  "omboBox\" id=\"panel-combobox\"><property name=\"visible\">True</proper"
  "ty><property name=\"model\">panel-store</property><child><object class="
  "\"GtkCellRendererText\" id=\"cellrenderertext2\"/><attributes><attribut"
  "e name=\"text\">0</attribute></attributes></child></object><packing><pr"
  "operty name=\"position\">0</property></packing></child><child><object c"
  "lass=\"GtkButton\" id=\"panel-add\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">True</property><property name=\"rec"
  "eives_default\">True</property><property name=\"tooltip_text\" translat"
  "able=\"yes\">Add a new panel</property><child><object class=\"GtkImage\""
  " id=\"image1\"><property name=\"visible\">True</property><property name"
  "=\"stock\">gtk-add</property></object></child></object><packing><proper"
  "ty name=\"expand\">False</property><property name=\"position\">1</prope"
  "rty></packing></child><child><object class=\"GtkButton\" id=\"panel-rem"
  "ove\"><property name=\"visible\">True</property><property name=\"sensit"
  "ive\">False</property><property name=\"can_focus\">True</property><prop"
  "erty name=\"receives_default\">True</property><property name=\"tooltip_"
  "text\" translatable=\"yes\">Remove the currently selected panel</proper"
  "ty><child><object class=\"GtkImage\" id=\"image2\"><property name=\"vis"
  "ible\">True</property><property name=\"stock\">gtk-remove</property></o"
  "bject></child></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"position\">2</property></packing></child></object><"
  "packing><property name=\"expand\">False</property><property name=\"posi"
  "tion\">0</property></packing></child><child><object class=\"GtkNotebook"
  "\" id=\"notebook\"><property name=\"visible\">True</property><property "
  "name=\"sensitive\">False</property><property name=\"can_focus\">True</p"
  "roperty><child><object class=\"GtkVBox\" id=\"vbox2\"><property name=\""
  "visible\">True</property><property name=\"border_width\">6</property><p"
  "roperty name=\"orientation\">vertical</property><property name=\"spacin"
  "g\">6</property><child><object class=\"GtkFrame\" id=\"frame1\"><proper"
  "ty name=\"visible\">True</property><property name=\"label_xalign\">0</p"
  "roperty><property name=\"shadow_type\">none</property><child><object cl"
  "ass=\"GtkAlignment\" id=\"alignment1\"><property name=\"visible\">True<"
  "/property><property name=\"left_padding\">12</property><child><object c"
  "lass=\"GtkVBox\" id=\"vbox3\"><property name=\"visible\">True</property"
  "><property name=\"border_width\">6</property><property name=\"orientati"
  "on\">vertical</property><property name=\"spacing\">6</property><child><"
  "object class=\"GtkHBox\" id=\"hbox1\"><property name=\"visible\">True</"
  "property><property name=\"spacing\">12</property><child><object class=\""
  "GtkLabel\" id=\"label1\"><property name=\"visible\">True</property><pro"
  "perty name=\"xalign\">0</property><property name=\"label\" translatable"
  "=\"yes\">_Orientation:</property><property name=\"use_underline\">True<"
  "/property><property name=\"wrap_mode\">word-char</property><property na"
  "me=\"mnemonic_widget\">horizontal</property></object><packing><property"
  " name=\"expand\">False</property><property name=\"position\">0</propert"
  "y></packing></child><child><object class=\"GtkComboBox\" id=\"horizonta"
  "l\"><property name=\"visible\">True</property><property name=\"model\">"
  "orientation-store</property><child><object class=\"GtkCellRendererText\""
  " id=\"cellrenderertext1\"/><attributes><attribute name=\"text\">0</attr"
  "ibute></attributes></child></object><packing><property name=\"expand\">"
  "False</property><property name=\"position\">1</property></packing></chi"
  "ld></object><packing><property name=\"position\">0</property></packing>"
  "</child><child><object class=\"GtkHBox\" id=\"output-box\"><property na"
  "me=\"visible\">True</property><property name=\"spacing\">12</property><"
  "child><object class=\"GtkLabel\" id=\"label13\"><property name=\"visibl"
  "e\">True</property><property name=\"xalign\">0</property><property name"
  "=\"label\" translatable=\"yes\">O_utput:</property><property name=\"use"
  "_underline\">True</property><property name=\"mnemonic_widget\">output-n"
  "ame</property></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"position\">0</property></packing></child><child><ob"
  "ject class=\"GtkComboBox\" id=\"output-name\"><property name=\"visible\""
  ">True</property><property name=\"model\">output-store</property><child>"
  "<object class=\"GtkCellRendererText\" id=\"cellrenderertext3\"/><attrib"
  "utes><attribute name=\"text\">1</attribute></attributes></child></objec"
  "t><packing><property name=\"expand\">False</property><property name=\"p"
  "osition\">1</property></packing></child></object><packing><property nam"
  "e=\"position\">1</property></packing></child><child><object class=\"Gtk"
  "CheckButton\" id=\"span-monitors\"><property name=\"label\" translatabl"
  "e=\"yes\">Span mo_nitors</property><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">True</property><property name=\"rece"
  "ives_default\">False</property><property name=\"tooltip_text\" translat"
  "able=\"yes\">Select this option to extend the panel over multiple monit"
  "ors.</property><property name=\"use_underline\">True</property><propert"
  "y name=\"draw_indicator\">True</property></object><packing><property na"
  "me=\"position\">2</property></packing></child><child><object class=\"Gt"
  "kCheckButton\" id=\"position-locked\"><property name=\"label\" translat"
  "able=\"yes\">_Lock panel</property><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">True</property><property name=\"rece"
  "ives_default\">False</property><property name=\"tooltip_text\" translat"
  "able=\"yes\">Select this option to hide the handles of the panel and lo"
  "ck its position.</property><property name=\"use_underline\">True</prope"
  "rty><property name=\"draw_indicator\">True</property></object><packing>"
  "<property name=\"position\">3</property></packing></child><child><objec"
  "t class=\"GtkCheckButton\" id=\"autohide\"><property name=\"label\" tra"
  "nslatable=\"yes\">Automatically show and _hide the panel</property><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">True"
  "</property><property name=\"receives_default\">False</property><propert"
  "y name=\"tooltip_text\" translatable=\"yes\">Select this option to hide"
  " the panel when the pointer is not above it. This only works when the p"
  "anel is attached to a screen edge.</property><property name=\"use_under"
  "line\">True</property><property name=\"draw_indicator\">True</property>"
  "</object><packing><property name=\"position\">4</property></packing></c"
  "hild></object></child></object></child><child type=\"label\"><object cl"
  "ass=\"GtkLabel\" id=\"label2\"><property name=\"visible\">True</propert"
  "y><property name=\"label\" translatable=\"yes\">General</property><attr"
  "ibutes><attribute name=\"weight\" value=\"bold\"/></attributes></object"
  "></child></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"position\">0</property></packing></child><child><object "
  "class=\"GtkFrame\" id=\"frame2\"><property name=\"visible\">True</prope"
  "rty><property name=\"label_xalign\">0</property><property name=\"shadow"
  "_type\">none</property><child><object class=\"GtkAlignment\" id=\"align"
  "ment2\"><property name=\"visible\">True</property><property name=\"left"
  "_padding\">12</property><child><object class=\"GtkTable\" id=\"table1\""
  "><property name=\"visible\">True</property><property name=\"border_widt"
  "h\">6</property><property name=\"n_rows\">3</property><property name=\""
  "n_columns\">2</property><property name=\"column_spacing\">12</property>"
  "<property name=\"row_spacing\">6</property><child><object class=\"GtkLa"
  "bel\" id=\"label3\"><property name=\"visible\">True</property><property"
  " name=\"xalign\">0</property><property name=\"label\" translatable=\"ye"
  "s\">_Size (pixels):</property><property name=\"use_underline\">True</pr"
  "operty><property name=\"mnemonic_widget\">size-scale</property></object"
  "><packing><property name=\"x_options\">GTK_FILL</property></packing></c"
  "hild><child><object class=\"GtkLabel\" id=\"label4\"><property name=\"v"
  "isible\">True</property><property name=\"xalign\">0</property><property"
  " name=\"label\" translatable=\"yes\">L_ength (%):</property><property n"
  "ame=\"use_underline\">True</property><property name=\"mnemonic_widget\""
  ">length-scale</property></object><packing><property name=\"top_attach\""
  ">1</property><property name=\"bottom_attach\">2</property><property nam"
  "e=\"x_options\">GTK_FILL</property></packing></child><child><object cla"
  "ss=\"GtkHScale\" id=\"length-scale\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">True</property><property name=\"up"
  "date_policy\">discontinuous</property><property name=\"adjustment\">len"
  "gth</property><property name=\"digits\">0</property><property name=\"va"
  "lue_pos\">right</property></object><packing><property name=\"left_attac"
  "h\">1</property><property name=\"right_attach\">2</property><property n"
  "ame=\"top_attach\">1</property><property name=\"bottom_attach\">2</prop"
  "erty></packing></child><child><object class=\"GtkHScale\" id=\"size-sca"
  "le\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">True</property><property name=\"update_policy\">discontinuous</pro"
  "perty><property name=\"adjustment\">size</property><property name=\"dig"
  "its\">0</property><property name=\"value_pos\">right</property></object"
  "><packing><property name=\"left_attach\">1</property><property name=\"r"
  "ight_attach\">2</property></packing></child><child><object class=\"GtkC"
  "heckButton\" id=\"length-adjust\"><property name=\"label\" translatable"
  "=\"yes\">A_utomatically increase the length</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">False</property><property name=\"tool"
  "tip_text\" translatable=\"yes\">Select this option to automatically inc"
  "rease the length of the panel if the plugins request more space.</prope"
  "rty><property name=\"use_underline\">True</property><property name=\"dr"
  "aw_indicator\">True</property></object><packing><property name=\"right_"
  "attach\">2</property><property name=\"top_attach\">2</property><propert"
  "y name=\"bottom_attach\">3</property></packing></child></object></child"
  "></object></child><child type=\"label\"><object class=\"GtkLabel\" id=\""
  "label5\"><property name=\"visible\">True</property><property name=\"lab"
  "el\" translatable=\"yes\" comments=\"I18N: name of the section (frame) "
  "in the panel preferences where the user can define the length and size "
  "of the panel\">Measurements</property><attributes><attribute name=\"wei"
  "ght\" value=\"bold\"/></attributes></object></child></object><packing><"
  "property name=\"expand\">False</property><property name=\"position\">1<"
  "/property></packing></child></object></child><child type=\"tab\"><objec"
  "t class=\"GtkLabel\" id=\"label6\"><property name=\"visible\">True</pro"
  "perty><property name=\"label\" translatable=\"yes\">D_isplay</property>"
  "<property name=\"use_underline\">True</property></object><packing><prop"
  "erty name=\"tab_fill\">False</property></packing></child><child><object"
  " class=\"GtkVBox\" id=\"vbox7\"><property name=\"visible\">True</proper"
  "ty><property name=\"border_width\">6</property><property name=\"orienta"
  "tion\">vertical</property><property name=\"spacing\">6</property><child"
  "><object class=\"GtkFrame\" id=\"frame3\"><property name=\"visible\">Tr"
  "ue</property><property name=\"label_xalign\">0</property><property name"
  "=\"shadow_type\">none</property><child><object class=\"GtkAlignment\" i"
  "d=\"alignment3\"><property name=\"visible\">True</property><property na"
  "me=\"left_padding\">12</property><child><object class=\"GtkVBox\" id=\""
  "vbox4\"><property name=\"visible\">True</property><property name=\"bord"
  "er_width\">6</property><property name=\"orientation\">vertical</propert"
  "y><property name=\"spacing\">6</property><child><object class=\"GtkHBox"
  "\" id=\"hbox2\"><property name=\"visible\">True</property><property nam"
  "e=\"spacing\">12</property><child><object class=\"GtkLabel\" id=\"label"
  "7\"><property name=\"visible\">True</property><property name=\"xalign\""
  ">0</property><property name=\"label\" translatable=\"yes\">_Style:</pro"
  "perty><property name=\"use_underline\">True</property><property name=\""
  "mnemonic_widget\">background-style</property></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"position\">0</proper"
  "ty></packing></child><child><object class=\"GtkComboBox\" id=\"backgrou"
  "nd-style\"><property name=\"visible\">True</property><property name=\"m"
  "odel\">styles-store</property><child><object class=\"GtkCellRendererTex"
  "t\" id=\"cellrenderertext4\"/><attributes><attribute name=\"text\">0</a"
  "ttribute></attributes></child></object><packing><property name=\"expand"
  "\">False</property><property name=\"position\">1</property></packing></"
  "child></object><packing><property name=\"position\">0</property></packi"
  "ng></child><child><object class=\"GtkHBox\" id=\"bg-alpha-box\"><proper"
  "ty name=\"visible\">True</property><property name=\"spacing\">12</prope"
  "rty><child><object class=\"GtkLabel\" id=\"label15\"><property name=\"v"
  "isible\">True</property><property name=\"xalign\">0</property><property"
  " name=\"label\" translatable=\"yes\">_Alpha:</property><property name=\""
  "use_underline\">True</property><property name=\"mnemonic_widget\">bg-al"
  "pha-scale</property></object><packing><property name=\"expand\">False</"
  "property><property name=\"position\">0</property></packing></child><chi"
  "ld><object class=\"GtkHScale\" id=\"bg-alpha-scale\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">True</property><pr"
  "operty name=\"tooltip_text\" translatable=\"yes\">Alpha value of the pa"
  "nel background, with 0 being fully transparent and 100 fully opaque.</p"
  "roperty><property name=\"adjustment\">background-alpha</property><prope"
  "rty name=\"digits\">0</property><property name=\"value_pos\">right</pro"
  "perty></object><packing><property name=\"position\">1</property></packi"
  "ng></child></object><packing><property name=\"position\">1</property></"
  "packing></child><child><object class=\"GtkHBox\" id=\"bg-color-box\"><p"
  "roperty name=\"visible\">True</property><property name=\"spacing\">12</"
  "property><child><object class=\"GtkLabel\" id=\"label16\"><property nam"
  "e=\"visible\">True</property><property name=\"xalign\">0</property><pro"
  "perty name=\"label\" translatable=\"yes\">C_olor:</property><property n"
  "ame=\"use_underline\">True</property><property name=\"mnemonic_widget\""
  ">background-color</property></object><packing><property name=\"expand\""
  ">False</property><property name=\"position\">0</property></packing></ch"
  "ild><child><object class=\"GtkColorButton\" id=\"background-color\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Tru"
  "e</property><property name=\"receives_default\">True</property><propert"
  "y name=\"title\" translatable=\"yes\">Pick a Panel Color</property><pro"
  "perty name=\"color\">#000000000000</property></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"position\">1</proper"
  "ty></packing></child></object><packing><property name=\"position\">2</p"
  "roperty></packing></child><child><object class=\"GtkHBox\" id=\"bg-imag"
  "e-box\"><property name=\"visible\">True</property><property name=\"spac"
  "ing\">12</property><child><object class=\"GtkLabel\" id=\"label19\"><pr"
  "operty name=\"visible\">True</property><property name=\"xalign\">0</pro"
  "perty><property name=\"label\" translatable=\"yes\">_File:</property><p"
  "roperty name=\"use_underline\">True</property><property name=\"mnemonic"
  "_widget\">background-image</property></object><packing><property name=\""
  "expand\">False</property><property name=\"position\">0</property></pack"
  "ing></child><child><object class=\"GtkFileChooserButton\" id=\"backgrou"
  "nd-image\"><property name=\"visible\">True</property><property name=\"t"
  "itle\" translatable=\"yes\">Select A Background Image</property></objec"
  "t><packing><property name=\"position\">1</property></packing></child></"
  "object><packing><property name=\"position\">3</property></packing></chi"
  "ld></object></child></object></child><child type=\"label\"><object clas"
  "s=\"GtkLabel\" id=\"label8\"><property name=\"visible\">True</property>"
  "<property name=\"label\" translatable=\"yes\">Background</property><att"
  "ributes><attribute name=\"weight\" value=\"bold\"/></attributes></objec"
  "t></child></object><packing><property name=\"expand\">False</property><"
  "property name=\"position\">0</property></packing></child><child><object"
  " class=\"GtkFrame\" id=\"composited\"><property name=\"visible\">True</"
  "property><property name=\"label_xalign\">0</property><property name=\"s"
  "hadow_type\">none</property><child><object class=\"GtkAlignment\" id=\""
  "alignment4\"><property name=\"visible\">True</property><property name=\""
  "left_padding\">12</property><child><object class=\"GtkTable\" id=\"tabl"
  "e2\"><property name=\"visible\">True</property><property name=\"border_"
  "width\">6</property><property name=\"n_rows\">2</property><property nam"
  "e=\"n_columns\">2</property><property name=\"column_spacing\">12</prope"
  "rty><property name=\"row_spacing\">6</property><child><object class=\"G"
  "tkLabel\" id=\"label9\"><property name=\"visible\">True</property><prop"
  "erty name=\"xalign\">0</property><property name=\"label\" translatable="
  "\"yes\" comments=\"I18N: label for the enter transparency slider\">_Ent"
  "er:</property><property name=\"use_underline\">True</property><property"
  " name=\"mnemonic_widget\">enter-opacity-scale</property></object><packi"
  "ng><property name=\"x_options\">GTK_FILL</property></packing></child><c"
  "hild><object class=\"GtkLabel\" id=\"label10\"><property name=\"visible"
  "\">True</property><property name=\"xalign\">0</property><property name="
  "\"label\" translatable=\"yes\" comments=\"I18N: label for the leave tra"
  "nsparency slider\">_Leave:</property><property name=\"use_underline\">T"
  "rue</property><property name=\"mnemonic_widget\">leave-opacity-scale</p"
  "roperty></object><packing><property name=\"top_attach\">1</property><pr"
  "operty name=\"bottom_attach\">2</property><property name=\"x_options\">"
  "GTK_FILL</property></packing></child><child><object class=\"GtkHScale\""
  " id=\"enter-opacity-scale\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">True</property><property name=\"tooltip_tex"
  "t\" translatable=\"yes\">Transparency when the pointer is hovering over"
  " the panel, with 0 being fully transparent and 100 fully opaque.</prope"
  "rty><property name=\"adjustment\">enter-opacity</property><property nam"
  "e=\"digits\">0</property><property name=\"value_pos\">right</property><"
  "/object><packing><property name=\"left_attach\">1</property><property n"
  "ame=\"right_attach\">2</property></packing></child><child><object class"
  "=\"GtkHScale\" id=\"leave-opacity-scale\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">True</property><property name"
  "=\"tooltip_text\" translatable=\"yes\">Transparency when the pointer is"
  " not hovering over the panel, with 0 being fully transparent and 100 fu"
  "lly opaque.</property><property name=\"adjustment\">leave-opacity</prop"
  "erty><property name=\"digits\">0</property><property name=\"value_pos\""
  ">right</property></object><packing><property name=\"left_attach\">1</pr"
  "operty><property name=\"right_attach\">2</property><property name=\"top"
  "_attach\">1</property><property name=\"bottom_attach\">2</property></pa"
  "cking></child></object></child></object></child><child type=\"label\"><"
  "object class=\"GtkLabel\" id=\"label11\"><property name=\"visible\">Tru"
  "e</property><property name=\"label\" translatable=\"yes\">Opacity</prop"
  "erty><attributes><attribute name=\"weight\" value=\"bold\"/></attribute"
  "s></object></child></object><packing><property name=\"expand\">False</p"
  "roperty><property name=\"position\">1</property></packing></child></obj"
  "ect><packing><property name=\"position\">1</property></packing></child>"
  "<child type=\"tab\"><object class=\"GtkLabel\" id=\"label12\"><property"
  " name=\"visible\">True</property><property name=\"label\" translatable="
  "\"yes\">Appeara_nce</property><property name=\"use_underline\">True</pr"
  "operty></object><packing><property name=\"position\">1</property><prope"
  "rty name=\"tab_fill\">False</property></packing></child><child><object "
  "class=\"GtkHBox\" id=\"hbox4\"><property name=\"visible\">True</propert"
  "y><property name=\"border_width\">6</property><property name=\"spacing\""
  ">6</property><child><object class=\"GtkScrolledWindow\" id=\"scrolledwi"
  "ndow3\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">True</property><property name=\"hscrollbar_policy\">automatic</"
  "property><property name=\"vscrollbar_policy\">automatic</property><prop"
  "erty name=\"shadow_type\">etched-in</property><child><object class=\"Gt"
  "kTreeView\" id=\"item-treeview\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">True</property><property name=\"header"
  "s_visible\">False</property><property name=\"rules_hint\">True</propert"
  "y><property name=\"enable_search\">False</property></object></child></o"
  "bject><packing><property name=\"position\">0</property></packing></chil"
  "d><child><object class=\"GtkVBox\" id=\"vbox6\"><property name=\"visibl"
  "e\">True</property><property name=\"orientation\">vertical</property><p"
  "roperty name=\"spacing\">6</property><child><object class=\"GtkButton\""
  " id=\"item-up\"><property name=\"visible\">True</property><property nam"
  "e=\"sensitive\">False</property><property name=\"can_focus\">True</prop"
  "erty><property name=\"receives_default\">True</property><property name="
  "\"tooltip_text\" translatable=\"yes\">Move currently selected item up b"
  "y one row</property><child><object class=\"GtkImage\" id=\"image3\"><pr"
  "operty name=\"visible\">True</property><property name=\"stock\">gtk-go-"
  "up</property></object></child></object><packing><property name=\"expand"
  "\">False</property><property name=\"position\">0</property></packing></"
  "child><child><object class=\"GtkButton\" id=\"item-down\"><property nam"
  "e=\"visible\">True</property><property name=\"sensitive\">False</proper"
  "ty><property name=\"can_focus\">True</property><property name=\"receive"
  "s_default\">True</property><property name=\"tooltip_text\" translatable"
  "=\"yes\">Move currently selected item down by one row</property><child>"
  "<object class=\"GtkImage\" id=\"image4\"><property name=\"visible\">Tru"
  "e</property><property name=\"stock\">gtk-go-down</property></object></c"
  "hild></object><packing><property name=\"expand\">False</property><prope"
  "rty name=\"position\">1</property></packing></child><child><object clas"
  "s=\"GtkButton\" id=\"item-add\"><property name=\"visible\">True</proper"
  "ty><property name=\"sensitive\">False</property><property name=\"can_fo"
  "cus\">True</property><property name=\"receives_default\">True</property"
  "><property name=\"tooltip_text\" translatable=\"yes\">Add new item to t"
  "his panel</property><child><object class=\"GtkImage\" id=\"image5\"><pr"
  "operty name=\"visible\">True</property><property name=\"stock\">gtk-add"
  "</property></object></child></object><packing><property name=\"expand\""
  ">False</property><property name=\"position\">2</property></packing></ch"
  "ild><child><object class=\"GtkButton\" id=\"item-remove\"><property nam"
  "e=\"visible\">True</property><property name=\"sensitive\">False</proper"
  "ty><property name=\"can_focus\">True</property><property name=\"receive"
  "s_default\">True</property><property name=\"tooltip_text\" translatable"
  "=\"yes\">Remove currently selected item</property><child><object class="
  "\"GtkImage\" id=\"image6\"><property name=\"visible\">True</property><p"
  "roperty name=\"stock\">gtk-remove</property></object></child></object><"
  "packing><property name=\"expand\">False</property><property name=\"posi"
  "tion\">3</property></packing></child><child><object class=\"GtkButton\""
  " id=\"item-properties\"><property name=\"visible\">True</property><prop"
  "erty name=\"sensitive\">False</property><property name=\"can_focus\">Tr"
  "ue</property><property name=\"receives_default\">True</property><proper"
  "ty name=\"tooltip_text\" translatable=\"yes\">Edit the currently select"
  "ed item</property><child><object class=\"GtkImage\" id=\"image7\"><prop"
  "erty name=\"visible\">True</property><property name=\"stock\">gtk-prope"
  "rties</property></object></child></object><packing><property name=\"exp"
  "and\">False</property><property name=\"position\">4</property></packing"
  "></child><child><object class=\"GtkButton\" id=\"item-about\"><property"
  " name=\"visible\">True</property><property name=\"sensitive\">False</pr"
  "operty><property name=\"can_focus\">True</property><property name=\"rec"
  "eives_default\">True</property><property name=\"tooltip_text\" translat"
  "able=\"yes\">Show about information of the currently selected item</pro"
  "perty><child><object class=\"GtkImage\" id=\"image8\"><property name=\""
  "visible\">True</property><property name=\"stock\">gtk-about</property><"
  "/object></child></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"position\">5</property></packing></child></object"
  "><packing><property name=\"expand\">False</property><property name=\"po"
  "sition\">1</property></packing></child></object><packing><property name"
  "=\"position\">2</property></packing></child><child type=\"tab\"><object"
  " class=\"GtkLabel\" id=\"label14\"><property name=\"visible\">True</pro"
  "perty><property name=\"label\" translatable=\"yes\">Ite_ms</property><p"
  "roperty name=\"use_underline\">True</property></object><packing><proper"
  "ty name=\"position\">2</property><property name=\"tab_fill\">False</pro"
  "perty></packing></child></object><packing><property name=\"position\">1"
  "</property></packing></child></object><packing><property name=\"positio"
  "n\">1</property></packing></child><child internal-child=\"action_area\""
  "><object class=\"GtkHButtonBox\" id=\"dialog-action_area1\"><property n"
  "ame=\"visible\">True</property><property name=\"layout_style\">end</pro"
  "perty><child><object class=\"GtkButton\" id=\"button-close\"><property "
  "name=\"label\">gtk-close</property><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">True</property><property name=\"rece"
  "ives_default\">True</property><property name=\"use_stock\">True</proper"
  "ty></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">False</property><property name=\"position\">0</property"
  "></packing></child><child><object class=\"GtkButton\" id=\"button-help\""
  "><property name=\"label\">gtk-help</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">True</property><property name=\"use_stock\">Tr"
  "ue</property></object><packing><property name=\"expand\">False</propert"
  "y><property name=\"fill\">False</property><property name=\"position\">1"
  "</property><property name=\"secondary\">True</property></packing></chil"
  "d></object><packing><property name=\"expand\">False</property><property"
  " name=\"pack_type\">end</property><property name=\"position\">0</proper"
  "ty></packing></child></object></child><action-widgets><action-widget re"
  "sponse=\"0\">button-close</action-widget><action-widget response=\"1\">"
  "button-help</action-widget></action-widgets></object></interface>"
};

static const unsigned panel_preferences_dialog_ui_length = 28700u;

